### ISSUE TITLE
Error 500: Class BaconQrCode\Renderer\Image\Svg not found

### ISSUE THREAD

**Issue by jaxtheking** [mageplaza/magento-2-two-factor-authentication#10]
In Magento 2.4.0, the BaconQrCode library is already installed (v2.0.2).
It seems your module is not compatible with this version as the class BaconQrCode\Renderer\Image\Svg is no longer used.

The code in Helper/Data.php should be changed from:
```
use BaconQrCode\Renderer\Image\Svg;
use BaconQrCode\Writer;
...
$renderer = new Svg();
$renderer->setHeight(171);
$renderer->setWidth(171);
$renderer->setMargin(0);
```
to:
```
use BaconQrCode\Renderer\ImageRenderer;
use BaconQrCode\Renderer\Image\SvgImageBackEnd;
use BaconQrCode\Renderer\RendererStyle\RendererStyle;
use BaconQrCode\Writer;
...
$renderer = new ImageRenderer(
        new RendererStyle(171),
        new SvgImageBackEnd()
);
```

Hope that helps,
Luca

**Comment by Shinichi69** [comment]
Hi @jaxtheking 

Thanks for your feedback!

We've updated this in the develop branch:
- https://github.com/mageplaza/magento-2-two-factor-authentication/tree/develop
You can try again with this version for Magento 2.4.

We'll also soon merge this version into the master branch.

Thanks so much!

**Comment by jaxtheking** [comment]
You're welcome. In the end I ended up not using the module (although I see how it improves on the default Magento module) as I needed it to be able to disable 2FA only for one specific user (or user role), who connects via the REST API in order to pull our products.
Do you know if such a feature is in the pipeline? I guess not but it's worth a shot :)

**Comment by Shinichi69** [comment]
Hi @jaxtheking 

I truly apologize for the inconvenience.
Unfortunately, the current version has not supported this function yet. I'm so sorry about that. 
However, I will surely note it to our developer to consider developing it in the future.

If you have no other issue, I'll close this issue.

Thank you very much for your feedback.

**Comment by selectj** [comment]
Any chance of this actually being released? Installing the module via composer pulls an older version that still contains this issue, so I've had to manually fix it in my local copy.

If this could be merged into master and released so that the fixed version is on Packagist, that would be much appreciated!

**Comment by ismailcaakir** [comment]
Do you have a solution?

Please check.

https://github.com/Bacon/BaconQrCode/tree/1.0.0

https://github.com/Bacon/BaconQrCode/tree/2.0.3

**Comment by selectj** [comment]
The solution is in the thread

**Comment by ismailcaakir** [comment]
> The solution is in the thread
> […](#)
> Sent from my iPhone
> On 15 Feb 2021, at 19:53, İsmail Çakır ***@***.***> wrote: ﻿ Do you have a solution? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Oh sorry, I'm too distracted. Thank you 🙏
