### ISSUE TITLE
main.CRITICAL: Class Mageplaza\TwoFactorAuth\Model\Auth does not exist

### ISSUE THREAD

**Issue by Mirifik** [mageplaza/magento-2-two-factor-authentication#12]
Hello Team,
I have issue with modules.
Frontend:   http://prntscr.com/wfuadv
Backend:   http://prntscr.com/wfuasl

[2021-01-04 09:16:41] main.CRITICAL: Class Mageplaza\TwoFactorAuth\Model\Auth does not exist {"report_id":"223936958559e1f610650516ee947bda6726a26158e2ba434f86b9c6c36bdf30","exception":"[object] (ReflectionException(code: -1): Class Mageplaza\\TwoFactorAuth\\Model\\Auth does not exist at /home/ipcgenev/public_html/vendor/magento/framework/Code/Reader/ClassReader.php:26)"} []

**Comment by Shinichi69** [comment]
Hi @Mirifik 

I’m Shin from Mageplaza and I will support you on this issue.

Have you installed our Core extension yet?
All extensions are based on the Core extension.
You can download the latest version of the Core extension here:
- https://github.com/mageplaza/module-core
Also, please install the library to support this extension:
- composer require sinergi/browser-detector
- composer require sonata-project/google-authenticator

Thanks so much!

**Comment by Mirifik** [comment]
Thank you very much, 
I will follow your instructions and get back to you once everything is okay.

King regards!

**Comment by Shinichi69** [comment]
Hi @Mirifik 

Yes, I'm looking forward to hearing from you.

Thanks so much!

**Comment by Mirifik** [comment]
Great,
Great, 
I found my home page and the backend but the Slides, products and buttons are not displayed.
I looked at the symlink but it doesn't work.

Frontend: http://prntscr.com/wfvfl9
Backend:  http://prntscr.com/wfvenp

**Comment by Shinichi69** [comment]
Hi @Mirifik 

Please run the upgrade and deploy again.
Then please try again.

Thanks so much!

**Comment by Mirifik** [comment]
Hello Shinichi69,
I always have the same display problem, my friend.
Frontend: http://prntscr.com/wfvfl9
Backend: http://prntscr.com/wfvenp

Please help!!

**Comment by Mirifik** [comment]
When i run comand line below I get 
composer require sinergi/browser-detector
composer require sonata-project/google-authenticator

Fatal error: Allowed memory size of 2097152 bytes exhausted (tried to allocate 4096 bytes) in phar:///opt/cpanel/composer/bin/composer/vendor/symfony/console/Helper/Table.php on line 40

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.ipcgenev@nl1-ts3 [~/public_html]#

**Comment by Shinichi69** [comment]
Hi @Mirifik 

Please try to disable our extension and try again to see if your problem still appears.

Regarding the problem with the composer, it seems to be a problem with the memory on your server.
Please try to download the library here:
- https://drive.google.com/drive/folders/1ZeSAvzWPDd7G57oxdSC3H-DIerb7aK5o?usp=sharing
Then copy them to the folder:
- <Magento_folder>/lib/internal/Mageplaza

Thanks so much!

**Comment by Mirifik** [comment]
Hi Shinichi69
I can't disable your extension because the links are off. 
It looks like a symlink problem. But it's not the case
http://prntscr.com/wfwg1b

**Comment by Mirifik** [comment]
Hi @Shinichi69 
I check on exception.log and I this error line again :

main.CRITICAL: Class Mageplaza\TwoFactorAuth\Model\Auth does not exist {"report_id":"223936958559e1f610650516ee947bda6726a26158e2ba434f86b9c6c36bdf30","exception":"[object] (ReflectionException(code: -1): Class Mageplaza\\TwoFactorAuth\\Model\\Auth does not exist at /home/ipcgenev/public_html/vendor/magento/framework/Code/Reader/ClassReader.php:26)"} []

**Comment by Mirifik** [comment]
Hello everything work very fine now by using this command line

php bin/magento s:up
php bin/magento s:s:d -f en_US fr_FR
php bin/magento c:f
