### ISSUE TITLE
Please share the new version.

### ISSUE THREAD

**Issue by ismailcaakir** [mageplaza/magento-2-two-factor-authentication#13]
#10 the error here can't be solved because of our dependency with your other modules.

Ex:
`Problem 1
    - mageplaza/magento-2-social-login 4.0.2 requires mageplaza/module-two-factor-authentication ^4.0.0 -> satisfiable by mageplaza/module-two-factor-authentication[4.0.0] but these conflict with your requirements or minimum-stability.
    - mageplaza/magento-2-social-login 4.0.2 requires mageplaza/module-two-factor-authentication ^4.0.0 -> satisfiable by mageplaza/module-two-factor-authentication[4.0.0] but these conflict with your requirements or minimum-stability.
    - mageplaza/magento-2-social-login 4.0.2 requires mageplaza/module-two-factor-authentication ^4.0.0 -> satisfiable by mageplaza/module-two-factor-authentication[4.0.0] but these conflict with your requirements or minimum-stability.
    - Installation request for mageplaza/magento-2-social-login v4.0.2 -> satisfiable by mageplaza/magento-2-social-login[4.0.2].`

Please share the new release.

**Comment by giaphn** [comment]
Hi,
I"m Shox from Mageplaza.
Can you please let me know how to reproduce your problem?
Thank you very much!

**Comment by giaphn** [comment]
Closed due no response within 7 days.
