### ISSUE TITLE
Incompatibility with M2.3.7-p1

### ISSUE THREAD

**Issue by mamsincl** [mageplaza/magento-2-two-factor-authentication#15]
Incompatibility with Magento 2.3.7-p1

due composer.json requirements, we are unable to create an installable set of packages 
```
    - Can only install one of: bacon/bacon-qr-code[1.0.3, 2.0.4].
    - Can only install one of: bacon/bacon-qr-code[2.0.4, 1.0.3].
    - Can only install one of: bacon/bacon-qr-code[1.0.3, 2.0.4].
```
`mageplaza/magento-2-social-login` is required in main **composer.json**, this module is installed as dependencies

possible fix:
require both ^2.0 and ^1.0.3 for package "bacon/bacon-qr-code": "^1.0.3",

**Comment by mamsincl** [comment]
fix
https://github.com/mageplaza/magento-2-two-factor-authentication/pull/16

**Comment by TeddyMageplaza** [comment]
Hello,

I am Teddy from Mageplaza Support Team. Our team really appreciate your help. We have updated the module and will release it as soon as possible.
Once again, thank you a lot for your help and we’re grateful for the trust you’ve placed in us. 

Have a nice week!

**Comment by mamsincl** [comment]
Hi @TeddyMageplaza ,

The freshly published version [1.1.2](https://github.com/mageplaza/magento-2-two-factor-authentication/releases/tag/v1.1.2) is still having the same composer conflict as before.

I updated my feature branch so the above PR is providing the fix for the conflict.

Origin: 
**msp/twofactorauth** (required as core solution) requiring **bacon/bacon-qr-code** as ^2.0 via dependency

**Comment by TeddyMageplaza** [comment]
Hi @mamsincl,

Thanks for the response and I am sorry for this inconvenience. Because you are using **Magento 2.3.7**, you absolutely can install the **_4.0.2_** version. It is fully compatible with your Magento.

About updating the **_composer.json_** file, we appreciate your contribution and will update it as soon as possible.

Have a nice day!

**Comment by mamsincl** [comment]
thanks, we are requesting "mageplaza/magento-2-social-login" as ^4.0 now - that resolved all the composer conflicts

**Comment by TeddyMageplaza** [comment]
Hi @mamsincl,

So if there is no issue left, I will close this issue.
Thank you so much!
Have a nice day!
