### ISSUE TITLE
Needs updating for M 2.4.4/PHP 8.1.x - Doesn't work

### ISSUE THREAD

**Issue by FadedOut** [mageplaza/magento-2-two-factor-authentication#19]
### Preconditions (*)
1. Magento 2.4.4
2. PHP 8.1.4

### Steps to reproduce (*)
1. Install Mageplaza Security which forces this module to install
2. Or just install this module
3. Try to log into Magento Admin with this module active

### Expected result (*)
1. Everything to work as intended

### Actual result (*)
1. Received an error while trying to log into admin (basic on admin page, error report in system.log)
2. Error posted below:

```
main.ERROR: Deprecated Functionality: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /home/******/public_html/vendor/mageplaza/module-two-factor-authentication/Helper/Data.php on line 139 [] []
main.CRITICAL: Exception: Deprecated Functionality: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /home/******/public_html/vendor/mageplaza/module-two-factor-authentication/Helper/Data.php on line 139 in /home/******/public_html/vendor/magento/framework/App/ErrorHandler.php:61
```

This error is common with a lot of my 3rd-party modules - it's the stack changes Magento did in 2.4.4 that these modules need to be updated for.

**Comment by ersvltan** [comment]
Hi @FadedOut ,

We faced this issue too. I raised a PR (#22) which fixes the error.

Kind regards,
Yersultan

**Comment by FadedOut** [comment]
Hello @ersvltan 

Thank you for this info. I actually had fixed it a little while ago by simply adding (string) like this

```
return explode(',', (string) $whitelistIp);
```

And it allowed me to log in. But I don't use it (magento has it's own 2fa but this comes included with some other module (security)) so I'm not sure if it actually worked with my change or not (it just didn't throw an error and stop me from being able to login to admin panel). 

But your fix looks much more complete and proper so I have implemented that and everything seems to still work. So, thanks again for the more proper fix 👍

**Comment by klou** [comment]
This extension/module also seems to be installed/required by Social Login, which has it's own share of issues.

Thanks for the fix.

**Comment by KhietNguyen83** [comment]
Hi @FadedOut ,
I'm Justin Mageplaza.
Thank you for your interest in our TwoFactorAuth module.
I read the comments and noticed that you have solved the problem.
We will update the bug in the new version and release it soon
Thank you very much!
