### ISSUE TITLE
Invalid argument exception

### ISSUE THREAD

**Issue by pocallaghan** [mageplaza/magento-2-two-factor-authentication#3]
On line 220 of `Model/Auth.php` the code uses a shorthand ternary to determine the argument passed to the `throwException` method.

```
self::throwException(
    $e->getMessage() ?: __('You did not sign in correctly or your account is temporarily disabled.')
);
```

The first argument for the throwException method is expected to be / type hinted as `Phase`, however if the original exception has a message, this will be passed instead (and it's a string).

**Comment by pocallaghan** [comment]
A potential solution may be to do something like:
```
$message = $e->getMessage() ?: 'You did not sign in correctly or your account is temporarily disabled.'
self::throwException(__($message));
```

**Comment by thaimageplaza** [comment]
Thank you for contacting us.
I will surely note it to our developer to consider developing it in the future so please look forward to this. Thank you very much for your feedback.
